### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Arsyad1105** [Vikassm73/plugin.video.botallen.hotstar#7]
I got error after entering OTP

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 216: invalid continuation byte

**Comment by Vikassm73** [comment]
What version of Kodi your using?

**Comment by Arsyad1105** [comment]
> What version of Kodi your using?

19.3

**Comment by Vikassm73** [comment]
Uninstall your addon first. Then install below addon

(Zip removed)

**Comment by Arsyad1105** [comment]
> Uninstall your addon first. Then install below addon
> 
> [plugin.video.hotstar.zip](https://github.com/Vikassm73/plugin.video.hotstar/files/10150949/plugin.video.hotstar.zip)

Still same error

**Comment by Vikassm73** [comment]
send me a debug log

**Comment by Arsyad1105** [comment]
2022-12-05 15:28:23.465 T:8222     INFO <general>: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:24.304 T:8222     INFO <general>: initializing python engine.
2022-12-05 15:28:24.306 T:8222     INFO <general>: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:24.388 T:8140     INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2022-12-05 15:28:25.260 T:8222     INFO <general>: initializing python engine.
2022-12-05 15:28:25.263 T:8222     INFO <general>: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:28.988 T:8222     INFO <general>: Python interpreter interrupted by user
2022-12-05 15:28:28.988 T:8226    ERROR <general>: Skipped 2 duplicate messages..
2022-12-05 15:28:28.988 T:8226    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.hotstar/resources/lib/main/settings/?_pickle_=80049519000000000000007d948c075f7469746c655f948c0853657474696e677394732e
2022-12-05 15:28:28.998 T:8140    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hotstar/resources/lib/main/settings/?_pickle_=80049519000000000000007d948c075f7469746c655f948c0853657474696e677394732e) failed
2022-12-05 15:28:29.015 T:8238     INFO <general>: initializing python engine.
2022-12-05 15:28:29.522 T:8238     INFO <general>: CPythonInvoker(2, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:30.170 T:8238     INFO <general>: initializing python engine.
2022-12-05 15:28:30.172 T:8238     INFO <general>: CPythonInvoker(2, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:30.936 T:8238     INFO <general>: initializing python engine.
2022-12-05 15:28:30.949 T:8140     INFO <general>: Loading skin file: DialogNumeric.xml, load type: KEEP_IN_MEMORY
2022-12-05 15:28:33.200 T:8186     INFO <general>: CPythonInvoker(0, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): script successfully run
2022-12-05 15:28:33.313 T:8186     INFO <general>: Python interpreter stopped
2022-12-05 15:28:44.119 T:8238    ERROR <general>: [Disney+-Hotstar.support] 'utf-8' codec can't decode byte 0xcf in position 216: invalid continuation byte
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/resources/lib/main.py", line 69, in login
                                                       api.doLogin()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/resources/lib/api.py", line 158, in doLogin
                                                       db["udata"] = json.loads(json.loads(
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/__init__.py", line 343, in loads
                                                       s = s.decode(detect_encoding(s), 'surrogatepass')
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 216: invalid continuation byte
2022-12-05 15:28:44.119 T:8238     INFO <general>: CPythonInvoker(2, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hotstar/addon.py): script successfully run
2022-12-05 15:28:48.056 T:8140     INFO <general>: CWinSystemAndroid::DestroyWindow
2022-12-05 15:28:48.190 T:8086  WARNING <general>: CPeripheralBusAndroid: failed to update input device with ID 2 because it couldn't be found
2022-12-05 15:28:48.190 T:8086  WARNING <general>: CPeripheralBusAndroid: failed to update input device with ID 4 because it couldn't be found

**Comment by Vikassm73** [comment]
Do you have a valid subscription?
First Logout and try to login
If same error then Install below zip.
Enable Debug log option in add-on settings (Your previous log was not a debug enabled log)
First log out and then try to login again
Send log by attaching kodi.log and send it to vikassm73@gmail.com

[plugin.video.hotstar.zip](https://github.com/Vikassm73/plugin.video.hotstar/files/10152574/plugin.video.hotstar.zip)

**Comment by Vikassm73** [comment]
Your country is Malaysia. I am surprise, how you manage to get OTP. In your profile try to change your name yourself or with the help of customer support in English which might be entered in your language. and re-try the login procedure.

**Comment by Arsyad1105** [comment]
Just change my profile name. Don't know the addon read the profile name. But now I got new issue that it said I don't have subscription even I have it.

**Comment by Vikassm73** [comment]
Even non premium content might not be working. Previously, was you able to play non premium content without login?

**Comment by Arsyad1105** [comment]
Just test, non premium content also not playing but no error.

**Comment by Vikassm73** [comment]
Sorry but it may not work for your region. https://www.hotstar.com/my not available here hence can not test it properly.

**Comment by Arsyad1105** [comment]
> Sorry but it may not work for your region. https://www.hotstar.com/my not available here hence can not test it properly.

You can register controld dns and set country to Malaysia. It have 30 days free trial. If you want to test using my hotstar account I can give you.

**Comment by Vikassm73** [comment]
Can you play anything (may be Series/Movie) without login?

**Comment by Arsyad1105** [comment]
> Can you play anything (may be Series/Movie) without login?

No, playback error

**Comment by Vikassm73** [comment]
check you email. New addon send

**Comment by Arsyad1105** [comment]
It's working now 😁

**Comment by Arsyad1105** [comment]
Can you make subtitle work too? In log it said 403 error for the subtitle link but when I copy the link and paste it on browser it just working. This problem still not fixed since the old addon from botallen.

**Comment by Vikassm73** [comment]
I will check if possible
